language: python
python: 2.7
sudo: false
cache:
  directories:
    - eggs
env:
  matrix:
    - PLONE_VERSION=4.3
install:
  - sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
  - sed -ie "s#versions-4.3#versions-$PLONE_VERSION#" buildout.cfg
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout -Nq
script:
  - bin/i18nextract canaimagnulinux.wizard
  - bin/i18nextract canaimagnulinux.userdata
#  - bin/i18nextract plone
  - bin/test
after_success:
  - bin/createcoverage -t "--layer=!Robot"
  - pip install -q coveralls
  - coveralls
after_failure:
  - bin/buildout annotate
  - firefox -v
#notifications:
#  email:
#    recipients:
#      - desarrolladores@canaima.softwarelibre.gob.ve
#    on_success: change
#    on_failure: change
#  irc:
#    channels:
#      - "irc.freenode.org#canaima"
#    on_success: change
#    on_failure: always