language: python
python: 2.7
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg -v 2.2.1
  - bin/buildout -c travis.cfg -N
script:
  - bin/i18n canaimagnulinux.wizard
  - bin/i18n canaimagnulinux.userdata
  - bin/i18n plone
  - bin/test
#notifications:
#  email:
#    recipients:
#      - desarrolladores@canaima.softwarelibre.gob.ve
#    on_success: change
#    on_failure: change
#  irc:
#    channels:
#      - "irc.freenode.org#canaima"
#    on_success: change
#    on_failure: always